server.port=5000

spring.datasource.url=jdbc:postgresql://localhost:5432/purchase_order_db
spring.datasource.username=postgres
spring.datasource.password=nishanth@123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
